### PR TITLE
Fix SyncWriter incompatibility with Transport::HTTP::Client

### LINKED ISSUE #903: undefined method `traces' for #<Datadog::Transport::HTTP::Client ... when using SyncWriter
Hello folks. I'm seeing the following error when trying to use SyncWriter in my specs:
```
#<Thread:0x00007ffb036a0c60@/Users/ynaidyon/.rvm/gems/ruby-2.6.5/gems/ddtrace-0.30.1/lib/ddtrace/sync_writer.rb:38 run> terminated with exception (report_on_exception is true):
/Users/ynaidyon/.rvm/gems/ruby-2.6.5/gems/ddtrace-0.30.1/lib/ddtrace/sync_writer.rb:53:in `flush_trace': 
undefined method `traces' for #<Datadog::Transport::HTTP::Client:0x00007ffb02b02c50> (NoMethodError)
```

I think it was broken around here: https://github.com/DataDog/dd-trace-rb/commit/46b685b087637a59d0daff6564482d9ee33aaa31#diff-34a63124ba72d0f43c54ea1cb77f78e5

### PR DESCRIPTION
**Pull request by delner**
The `SyncWriter` expects transports to respond to `#traces` but `Transport::HTTP::Client` only responds to `#send_traces`. This pull request fixes this incompatibility, and adds an integration test that verifies the `SyncWriter` can be used to send traces through end-to-end.

Fixes #903

### CODE REVIEW

File: test/sync_writer_test.rb [hunk 1]
```diff
@@ -1,61 +0,0 @@
-require 'minitest'
```
Comment (marcotc) [inline test/sync_writer_test.rb]: Nice work on migrating these 👏
