### PR TITLE
Fix Rails template layout name

### LINKED ISSUE #857: Error with Rails 6 when getting layout name for a template
I noticed that `rails.render_template` wasn't recording the template name as a tag.

Digging in it looks like the issue is here - https://github.com/DataDog/dd-trace-rb/blob/346634da8c40803fecad891c2cf524751a1dd78b/lib/ddtrace/contrib/action_view/instrumentation/template_renderer.rb#L113

Under Rails 6.0.1, I'm getting this error:
```
[1] pry(#<ActionView::TemplateRenderer>)> layout_name.try(:[], 'virtual_path')
NoMethodError: Could not render layout: undefined method `find_all' for "virtual_path":String
from <redacted>/.gem/ruby/2.6.3/gems/actionview-6.0.1/lib/action_view/layouts.rb:418:in `rescue in _default_layout'
Caused by NoMethodError: undefined method `find_all' for "virtual_path":String
from <redacted>/.gem/ruby/2.6.3/gems/actionview-6.0.1/lib/action_view/layouts.rb:327:in `_layout'
```

### PR DESCRIPTION
**Pull request by marcotc**
Fixes #857 

This PR fixes the retrieval of the `layout` property for the `ActionView` integration.

The approach I took was to use the `ActiveSupport` events that are published during template rendering.
These events have existed for all versions of Rails we support, but only since Rails 4.0 they exist in a useful state.

Before Rails 4.0, we only received one event at the end of the instrumentation, there were no separate "before" and "after" events. This prevent us from properly nesting `render_partial` spans inside their respective `render_template` span.

The reason our test suite did not capture this bug is because we explicitly set the `layout 'application'` in our controller during testing, while most users don't actually set it in their applications. A test case was added to prevent future regressions.

In sum, this PR implements `ActionView` integration through `ActiveSupport` events for Rails >= 4.0, and falls back to the existing patcher for Rails 3.X.

### CODE REVIEW

File: test/contrib/rails/errors_test.rb [hunk 1]
```diff
@@ -54,6 +54,8 @@ class TracingControllerTest < ActionController::TestCase
   end
 
   test 'missing rendering should close the template Span' do
+    skip 'Recent versions use events, and cannot suffer from this issue' if Rails.version >= '4.0.0'
```
Comment (marcotc) [inline test/contrib/rails/errors_test.rb]: For versions of Rails that do not support the event-based integration, we start a span for a `rails.render_template` even if that template does not exist in the application.
Rails then fails to load it and errs out.
This leaves us with a `rails.render_template` that we have to finish somehow, so we make it as an error span.

Ideally, this span wouldn't exist, as the application actually never got to start rendering something that doesn't exist. Besides, we already have error information in the parent span, so no additional information is conveyed with that "fake" span.

In the even-based implementation, that's the case: we do no have a span for a template that has never existed in first place. Rails won't even fire a "start rendering" event for it, as it gives up before it start to render.
This makes this specific test no relevant to the event-based implementation, as its main goal is to check that the nested missing `rails.render_template` span was successfully closed.

File: test/contrib/rails/rack_middleware_test.rb [hunk 2]
```diff
@@ -58,6 +58,7 @@ class FullStackTest < ActionDispatch::IntegrationTest
 
     assert_equal(render_span.name, 'rails.render_template')
     assert_equal(render_span.span_type, 'template')
+    assert_equal(render_span.service, Datadog.configuration[:rails][:service_name])
```
Comment (marcotc) [inline test/contrib/rails/rack_middleware_test.rb]: An extra test that seems to have been overlooked: I unintentionally broken this `render_span`'s service tag while making minor changes to the template rendering integration and no test failed.
I added this test, as it would have caught my mistake in first place, and it should provide a small safeguard for the future.

File: test/contrib/rails/errors_test.rb (hunk 1 above)
Comment (delner) [reply test/contrib/rails/errors_test.rb]: Okay, perhaps we should consider adding a comment that reminds us that these parts of code should be removed when we drop 3.2 support.

File: test/contrib/rails/rack_middleware_test.rb (hunk 2 above)
Comment (delner) [reply test/contrib/rails/rack_middleware_test.rb]: :+1:

File: test/contrib/rails/errors_test.rb (hunk 1 above)
Comment (marcotc) [reply test/contrib/rails/errors_test.rb]: By having the line `skip '...' if Rails.version >= '4.0.0'` was hoping that this would be sufficient for us to notice and remove it when dropping support for the last version of Ruby `3.X`.
