### PR TITLE
Fix HTTP circuit breaker

### LINKED ISSUE #1030: watchdog anomalies after upgrade to 0.35.1
Screenshot 2020-05-07 at 09 29 20

This correlates with a deploy which included the ddtrace upgrade from 0.34.2 to 0.35.1

Was there a change to sampling rates or something?

### PR DESCRIPTION
**Pull request by delner**
Fixes #1030 

After refactoring the transport for payload chunking in #840 (released in 0.35.0), it appears that the HTTP circuit breaker misread the transport and didn't flag Net::HTTP requests from the transport as it should have, causing traces to be produced erroneously.

This pull request changes the circuit breaker strategy; rather than to be dependent on reading transport internals and match host/port, it inspects the HTTP request itself for the tracer version header which should only be present on Datadog-made HTTP requests. It will prevent transport changes from causing this error to re-occur.

Note that this is still not optimal; if the trace library makes HTTP calls that do not have this header (which they always should), it will re-occur. We'll need to introduce a better trace-disabling mechanism in the transport itself.

### CODE REVIEW

File: spec/ddtrace/contrib/http/circuit_breaker_spec.rb [hunk 1]
```diff
@@ -0,0 +1,107 @@
+require 'spec_helper'
+
+require 'ddtrace'
+require 'ddtrace/contrib/http/circuit_breaker'
+
+RSpec.describe Datadog::Contrib::HTTP::CircuitBreaker do
```
Comment (pawelchcki) [inline spec/ddtrace/contrib/http/circuit_breaker_spec.rb:6]: Should we also test actual undesired behavior?
I.e. when transport is called and http integration is on -  we don't produce any extra traces/spans.

Comment (delner) [reply spec/ddtrace/contrib/http/circuit_breaker_spec.rb:6]: We could do this in a much fuller integration test, if we orchestrated all the components and asserted on the trace output... it would probably be a good idea to have this.

Only issue is its a bit tricky to coordinate the threads so that we have a reliable test that runs all the way through the HTTP layer, too. But I think we can do it, just not in this file. This is where the library would benefit from a better "integration test" suite that can black box test these kinds of things.

Comment (delner) [reply spec/ddtrace/contrib/http/circuit_breaker_spec.rb:6]: Okay, I added what amounts to a fairly simple integration test for this... it activates real instrumentation for all HTTP libraries and asserts that sending traces does not produce traces for any `Datadog::Tracer` by asserting `expect_any_instance_of(Datadog::Tracer).to_not receive(:trace)`.

It then tests this against the 3 different kinds of transports today, and against all our HTTP integrations (not just Net/HTTP, in case the adapter changes.) I feel a lot more comfortable with this kind of test in place.
