### PR TITLE
[rails] fixed error reporting when exceptions happen in the cache layer

### LINKED ISSUE #243: undefined local variable or method `payload`
https://github.com/DataDog/dd-trace-rb/blob/587f9a8c440ba688a7557c52e21cab1a4572e083/lib/ddtrace/contrib/rails/core_extensions.rb#L229

One of our specs blew up and so I'm wondering if `payload` should really be `raw_payload` in this case and in other cases in this file.  It seems like this may have been copied from a method where `payload` was defined.

Here is a partial stacktrace with some details elided:

```
       expected RuntimeError with message matching <elided details here> cache value: id=, name/, got #<NameError: undefined local variable or method `payload' for #<ActiveSupport::Cache::MemoryStore:0x007fbd3f009638>> with backtrace:
         # /Users/beisenhauer/.rvm/gems/ruby-2.3.1@minx/gems/ddtrace-0.9.1/lib/ddtrace/contrib/rails/core_extensions.rb:229:in `rescue in fetch'
         # /Users/beisenhauer/.rvm/gems/ruby-2.3.1@minx/gems/ddtrace-0.9.1/lib/ddtrace/contrib/rails/core_extensions.rb:224:in `fetch'
```

/cc @palazzem

### PR DESCRIPTION
**Pull request by palazzem**
### Overview

Closes #243
Fixed a bug when an `Exception` was raised in the cache layer.

### CODE REVIEW

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 1]
```diff
@@ -190,23 +190,23 @@ def patch_cache_store_read
...
             tracing_context: {}
           }
 
           begin
             # process and catch cache exceptions
-            Datadog::Contrib::Rails::ActiveSupport.start_trace_cache(raw_payload)
+            Datadog::Contrib::Rails::ActiveSupport.start_trace_cache(payload)
             read_without_datadog(*args, &block)
           rescue Exception => e
             payload[:exception] = [e.class.name, e.message]
```
Comment (palazzem) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: here it was called `payload`. Changed everything to `payload` for consistency with other instrumentation.

File: test/contrib/rails/cache_test.rb [hunk 2]
```diff
@@ -58,6 +58,26 @@ class CacheTracingTest < ActionController::TestCase
     assert_equal(span.get_tag('rails.cache.key'), 'custom-key')
   end
 
+  test 'cache exception handling' do
```
Comment (palazzem) [inline test/contrib/rails/cache_test.rb]: This test doesn't pass with the previous code.
