### PR TITLE
Fix losing original karafka trace after iterating through the messages with distributed_tracing on

### LINKED ISSUE #4873: [BUG]: Karafka's "worker.process" trace is lost after iterating the messages (when distributed tracing is enabled)
### Tracer Version(s)

2.19.0

### Ruby Version(s)

ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin23]

### Relevent Library and Version(s)

karafka 2.5.0

### Bug Report

When using the Karafka integration with distributed_tracing, the original trace is lost once we start iterating through the messages.

### Reproduction Code

1. First make sure Kafka (or a compatible platform) is running.
```bash
# I'm using Redpanda, a Kafka-compatible platform
$ docker run --rm -p 9092:9092 docker.redpanda.com/redpandadata/redpanda
```

2. Then, on a brand new rails repo:
```bash
# add karafka and datadog gems
$ bundle add karafka datadog
```
```ruby
# config/initializers/datadog.rb
Datadog.configure do |c|
  c.tracing.instrument :karafka, distributed_tracing: true, enabled: true
end

# karafka.rb
class KarafkaApp < Karafka::BaseConsumer
  setup do |config|
    config.kafka = { 'bootstrap.servers': '127.0.0.1:9092' }
  end

  routes.draw do
    topic :example do
      consumer ExampleConsumer
    end
  end
end

# app/consumers/example_consumer.rb
class ExampleConsumer < Karafka::BaseConsumer
  def consume
    log("before #each")

    messages.each do |message|
      log("inside #each")
      puts "doing some hard work!"
    end

    log("after #each")
  end

  def log(description)
    trace = Datadog::Tracing.active_trace
    span = Datadog::Tracing.active_span

    data = {id: trace&.id, name: trace&.name, resource: trace&.resource, parent_span_id: trace&.parent_span_id}
    puts "[consumer - #{description}] trace: #{data}"

    data = {id: span&.id, name: span&.name, resource: span&.resource, parent_id: span&.parent_id}
    puts "[consumer - #{description}] span: #{data}"
  end
end

# producing messages in a terminal
["msg1", "msg2"].each do |msg|
  Datadog::Tracing.trace("producer.#{msg}") do
    digest = Datadog::Tracing.active_trace.to_digest
    headers = {}
    Datadog::Tracing::Contrib::Karafka.inject(digest, headers)
    Karafka.producer.produce_async({
      topic: "example", payload: { foo: msg }.to_json, headers: headers
    })
  end
end
```

Result of the above code (with some colors to help visualizing). Note that the `consumer - after #each` lines don't have an active trace/span.
Image

### Error Logs

_No response_

### Operating System

_No response_

### How does Datadog help you?

_No response_

### PR DESCRIPTION
**Pull request by Drowze**
**What does this PR do?**

On the Karafka integration, when `distributed_tracing` is on, the original trace was lost after iterating through the messages. This PR aims to fix that ~and also add _span links_ linking the message traces with the parent consumer trace (so it's easier to find each other using the Datadog APM UI)~.

Fixes #4873

**Motivation:**
Fix and improve the Datadog Karafka support.

**Change log entry**

**Additional Notes:**

**How to test the change?**
See #4873 for a full testing snippet.

### CODE REVIEW

File: lib/datadog/tracing/contrib/karafka/patcher.rb [hunk 1]
```diff
@@ -24,24 +24,39 @@ def propagation
...
+                # correlate in the Datadog UI
+                if parent_span && span.parent_id != parent_span.id
+                  # add a link from the parent trace to the message span
+                  span_link = Tracing::SpanLink.new(parent_trace_digest)
+                  span.links << span_link
+
+                  # add a link from the current trace to the parent span
+                  span_link = Tracing::SpanLink.new(trace.to_digest)
+                  parent_span.links << span_link
+                end
```
Comment (Drowze) [inline lib/datadog/tracing/contrib/karafka/patcher.rb]: Please let me know your thoughts here! I understand that _"span links"_ are not very widely used here in the ruby sdk, but one challenge we have once we _continue a trace_ is co-relating the span with its "original parent". I think _span links_ are a great fit for solving that problem.

**Comment by Drowze** [comment]
Hey @marcotc @ivoanjo can you have a quick look here please? 🙇 

Would like to get this merged to not conflict with other Karafka/Waterdrop pull requests (e.g.: DataDog/dd-trace-rb#4874 - and also I want to open a new PR soon about turning off distributed tracing on a per-topic basis, see [here](https://github.com/Over-haul/dd-trace-rb/compare/karafka-patches...support-karafka-configuration-per-topic-backport))

**Comment by ivoanjo** [comment]
Err thanks for the patience, I've asked the team to take a look at this asap :)

**Comment by marcotc** [comment]
@Drowze I took a first pass and I need to allocate proper time to understand how we best want to present this kind of workflow (span links, directly linking, something else).

I have scheduled time to take a good look at this next week.

**Comment by p-datadog** [comment]
The repair to https://github.com/DataDog/dd-trace-rb/pull/4876 LGTM. Span links do not appear to be used in dd-trace-rb except in one place where an open telemetry trace is converted (mapped?) to a datadog trace. @Drowze how do you feel about moving the span link code into a separate PR and just leaving the fix in this PR?

**Comment by p-datadog** [comment]
Regarding span links: I read https://docs.datadoghq.com/tracing/trace_collection/span_links/ to try to understand their usage. The documentation page says the span links are for relationships other than parent/child. In this PR they are used for parent/child relationship? What is the actual gain/benefit?

File: lib/datadog/tracing/contrib/karafka/patcher.rb [hunk 2]
```diff
@@ -24,24 +24,39 @@ def propagation
...
                 else
                   message.metadata.headers
                 end
-                trace_digest = Karafka.extract(headers)
-                Datadog::Tracing.continue_trace!(trace_digest) if trace_digest
+                Karafka.extract(headers)
               end
 
-              Tracing.trace(Ext::SPAN_MESSAGE_CONSUME) do |span|
+              Tracing.trace(Ext::SPAN_MESSAGE_CONSUME, continue_from: trace_digest) do |span, trace|
```
Comment (p-datadog) [inline lib/datadog/tracing/contrib/karafka/patcher.rb:37]: Actually I am not sure this is correct. Is `continue_from` really meant for parent/child relationship?

**Comment by p-datadog** [comment]
Looking at this PR again I don't understand the fix. The problem is the parent trace gets reset somehow, therefore I would expect the fix to repair the reset. How is adding links fixing the reset?

**Comment by Drowze** [comment]
Coming back to this now - apologies for the delay 🙇 

> do you feel about moving the span link code into a separate PR and just leaving the fix in this PR?

Sure - sounds good to me. I understand that span links are not widely used at the moment and using them here just made the PR a bit confusing to review, so I'll move that part into a separate pull request - and we can continue discussing span links there.

@p-datadog I just rebased the PR with latest master and removed the code referring to span links - can you have another look please? 🙇

File: lib/datadog/tracing/contrib/karafka/patcher.rb (hunk 2 above)
Comment (Drowze) [reply lib/datadog/tracing/contrib/karafka/patcher.rb:37]: From what I can tell it serves the same purpose as `continue_trace!`. I learned about from this upgrade guide:
https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md#distributed-tracing

From my own testing:
* `Datadog::Tracing.continue_trace!(digest); foo`
  * continues the digest's trace
  * loses the original trace/span (i.e. the one before continue_trace was called)
* `Datadog::Tracing.continue_trace!(digest) { foo }`
  * continues the digest's trace **for the duration of the block**
  * restores the trace/span that existed before continue_trace was called after the block is finished
* `Datadog::Tracing.trace(..., continue_from: digest) { foo }`
  * continues the digest's trace **for the duration of the block**
  * restores the trace/span that existed before continue_trace was called after the block is finished

so i.e. these two are MOSTLY equivalent (according to my own testing):
```ruby
Datadog::Tracing.continue_trace!(digest) do
  Datadog::Tracing.trace("foo") { foo }
end

Datadog::Tracing.trace("foo", continue_from: digest) { foo }
```

Comment (Drowze) [reply lib/datadog/tracing/contrib/karafka/patcher.rb:37]: Expanding on:
> these two are MOSTLY equivalent

The difference between `#continue_trace(digest) (block form)` and `#trace(..., continue_from: digest)` is when `digest` is nil:

```ruby
def trace_continuation(wrapper)
  Datadog::Tracing.trace("consumer") do
    digest = false # simulating: `digest = if options[:distributed_tracing]`
    span = Datadog::Tracing.active_span
    puts "[before] trace_id=#{span.trace_id} span.id=#{span.id} span.parent_id=#{span.parent_id}"

    wrapper.call(digest) do
      span = Datadog::Tracing.active_span
      puts "[during] trace_id=#{span.trace_id} span.id=#{span.id} span.parent_id=#{span.parent_id}"
    end

    puts "[after] trace_id=#{span.trace_id} span.id=#{span.id} span.parent_id=#{span.parent_id}"
  end
end

puts "using Datadog::Tracing.continue_trace!(digest) (block form)"
wrapper = ->(digest, &block) { Datadog::Tracing.continue_trace!(digest) { Datadog::Tracing.trace("inner_trace", &block) } }
trace_continuation(wrapper)

puts ""

puts "using Datadog::Tracing.trace(..., continue_trace: digest)"
wrapper = ->(digest, &block) { Datadog::Tracing.trace("inner_trace", continue_from: digest, &block) }
trace_continuation(wrapper)
```

Output of the above:
```
using Datadog::Tracing.continue_trace!(digest) (block form)
[before] trace_id=139807686336161950925879642238038895865 span.id=3653922831996102169 span.parent_id=0
[during] trace_id=139807686336161950926050411474175911060 span.id=2786856155961870832 span.parent_id=0
[after] trace_id=139807686336161950926050411474175911060 span.id=2786856155961870832 span.parent_id=0

using Datadog::Tracing.trace(..., continue_trace: digest)
[before] trace_id=139807686336161950928502974401754510602 span.id=2239169915823954653 span.parent_id=0
[during] trace_id=139807686336161950928502974401754510602 span.id=801398174448484079 span.parent_id=2239169915823954653
[after] trace_id=139807686336161950928502974401754510602 span.id=801398174448484079 span.parent_id=2239169915823954653
```

File: lib/datadog/tracing/contrib/karafka/patcher.rb [hunk 3]
```diff
@@ -25,35 +25,34 @@ def propagation
...
               end
 
-              if Datadog::DataStreams.enabled?
-                begin
-                  headers = if message.metadata.respond_to?(:raw_headers)
-                    message.metadata.raw_headers
-                  else
-                    message.metadata.headers
+              Tracing.trace(Ext::SPAN_MESSAGE_CONSUME, continue_from: trace_digest) do |span, trace|
+                if Datadog::DataStreams.enabled?
```
Comment (Drowze) [inline lib/datadog/tracing/contrib/karafka/patcher.rb:38]: I wasn't too sure about it but I moved moved this _data stream_ block inside the message span (since `Tracing.trace` now also handles the trace continuation)
I don't think that's an issue but it's probably worth mentioning (cc @ericfirth)

File: spec/datadog/tracing/contrib/karafka/patcher_spec.rb [hunk 4]
```diff
@@ -53,6 +53,83 @@
...
+            # assert that the current trace re-set to the original trace after iterating the messages
+            expect(Datadog::Tracing.active_trace).to eq(consumer_trace)
+            expect(Datadog::Tracing.active_span).to eq(consumer_span)
+          end
+
+          expect(spans).to have(3).items
+
+          # assert that the message span is not continuation of the producer span
+          expect(span.parent_id).to eq(consumer_span.id)
+          expect(span.trace_id).to eq(consumer_trace.id)
```
Comment (p-datadog) [inline spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: In the other test, is consumer (the middle span, if I am understanding the logic correctly) expected to be a child of producer? Is that asserted somewhere?

**Review by p-datadog — COMMENTED** [review]
Thanks @Drowze for splitting the PR.

I think this PR look good but I am not an expert in the tracing side, I'll try to find another reviewer.

File: lib/datadog/tracing/contrib/karafka/patcher.rb (hunk 3 above)
Comment (ericfirth) [reply lib/datadog/tracing/contrib/karafka/patcher.rb:38]: this seems like it would be fine to me

**Review by ericfirth — APPROVED** [review]

File: spec/datadog/tracing/contrib/karafka/patcher_spec.rb (hunk 4 above)
Comment (Drowze) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: In these tests, the `consumer` span is never expected to be a child of any span. Referring to each test individually:

1. _`when the message has tracing headers, when distributed tracing is enabled, it continues the span that produced the message`_
    * `consumer` is a root span and it doesn't have any child spans
    * `producer` is a root span and it has one child span from iterating the messages(*)

2. _`when the message has tracing headers, when distributed tracing is not enabled, it does not continue the span that produced the message`_
    * `consumer` is a root span and it has one child span from iterating the messages(*)
    * `producer` is a root span and it doesn't have any child spans

Hope that makes sense! 🙇 

---
_(*) we create spans from iterating the messages as the karafka integration patches `::Karafka::Messages::Messages#each`_

Comment (Drowze) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: > _(*) we create spans from iterating the messages as the karafka integration patches ::Karafka::Messages::Messages#each_

I think that this might not be clear enough from our tests... The messages are being iterated here:
```ruby
# this creates a new span
expect(messages).to all(be_a(::Karafka::Messages::Message))

# ...

# in these expectations, `span` refers to the span created from iterating the messages
expect(span.parent_id).to eq(consumer_span.id)
expect(span.trace_id).to eq(consumer_trace.id)

# because of these `let`s (from the beginning of the file)
let(:span) do
  spans.find { |s| s.name == span_name }
end
let(:span_name) { Datadog::Tracing::Contrib::Karafka::Ext::SPAN_MESSAGE_CONSUME }
```

~I'll update the test now to use an explicit `each` and add a comment about it.~

Comment (Drowze) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: Just updated the test with comments better expliciting the test intentions - please let me know if it's more clear now 🙇 

---

_note: I didn't add an explicit `each` because this same pattern of relying on `expect(...).to all(...)` to create a span is used across pretty much all the tests in that file_

Comment (p-datadog) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: Thanks, I think I understand what you are saying, but it's strange to me that the iterating span changed from being under the producer to being under the consumer but there is no relationship between the producer and the consumer. Might be a question outside the scope of this PR.

File: lib/datadog/tracing/contrib/karafka/patcher.rb (hunk 3 above)
Comment (p-datadog) [reply lib/datadog/tracing/contrib/karafka/patcher.rb:38]: I will resolve this to clean up the PR.

File: lib/datadog/tracing/contrib/karafka/patcher.rb (hunk 2 above)
Comment (p-datadog) [reply lib/datadog/tracing/contrib/karafka/patcher.rb:37]: :+1: I think with the linking removed from this PR this is now clear to me.

File: spec/datadog/tracing/contrib/karafka/patcher_spec.rb (hunk 4 above)
Comment (Drowze) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: Iterating the message does not really change any spans - it's _continuing a trace_ that changes the parent/child relationship of spans.
In other words:
* when `distributed_tracing=true`, the message span is a _continuation_ of the span that created it (if any) (i.e.: the message span turns into a _child_ of the span who produced the message)
* when `distributed_tracing=false`, the message span is just a regular span (which _may_ have a parent - which in the case of theses tests is the `consumer` span who's iterating the messages)

Distributed tracing gets confusing quickly 😅

Comment (Drowze) [reply spec/datadog/tracing/contrib/karafka/patcher_spec.rb:141]: just fyi: I found [this issue](https://github.com/DataDog/dd-trace-rb/issues/2964) describing a similar use-case, so I've included our own use-case there as well (along with an example & screenshots)

**Comment by Drowze** [comment]
Hey Datadog team 👋  @vpellan @p-datadog @marcotc @ivoanjo 
Is there anything I can do to help moving this PR forward?

As of now we're having to use our own [dd-trace-rb fork](https://github.com/Over-haul/dd-trace-rb/compare/v2.22.0...Over-haul:karafka-patches) due to some issues/missing features around the Karafka/WaterDrop integration (our fork is the latest dd-trace-rb release (v2.22.0), plus this PR, #5120 and #5107).

**Comment by vpellan** [comment]
Hey @Drowze ! Thanks for pinging me, I'll take a look at it asap !

**Comment by p-datadog** [comment]
Hi @Drowze , I have this on my list as well. I am currently working on some time-sensitive fixes but after that is done (hopefully by end of week) I plan on getting this PR merged.

We don't currently have automation around community PRs - this is essentially the blocker.

**Comment by vpellan** [comment]
Running the CI here: https://github.com/DataDog/dd-trace-rb/pull/5192

**Review by vpellan — APPROVED** [review]
