### PR TITLE
Fix ActionView tracing contexts when span limit is reached

### LINKED ISSUE #445: Undefined method `span_id' for nil:NilClass with long requests
In our application we have very complicated and long listings with tons of html elements. It can take even 300+ seconds for the view to render.

Shorter listings render fine but for those longer ones we receive `status=500 error='ActionView::Template::Error: undefined method 'span_id' for nil:NilClass'`:

This error happens with ddtrace versions `>= 0.12.0`, downgrading to `0.11.4` helped for us.

Response:
```
method=GET path=/foo/6302256 format=html controller=FooController action=show status=500 error='ActionView::Template::Error: undefined method `span_id' for nil:NilClass' duration=165571.01 view=0.00 db=8886.01
```

View template looks about like this: (entries array may include 2000+ items...)
```
- entries.each do |entry|
  %tr
    %td
      .row
        = render partial: 'foo', locals: {foo: bar}
    %td
      .row
        = render partial: 'foo/items', locals: {foo: bar, items: bar.items(:one)}
    %td
      .row
        = render partial: 'foo/items', locals: {foo: bar, items: bar.items(:two)}
```

And inside items partial again:

```
items.each do |item|
  ...
end
```

Full trace:
```
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:133:in `current_span_id'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:106:in `ensure in render_with_datadog'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:109:in `render_with_datadog'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (4.2.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
haml (4.0.7) lib/haml/helpers.rb:89:in `non_haml'
haml (4.0.7) lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
app/views/foo/show.html.haml:22:in `_app_views_foo_show_html_haml___1150221759246532801_70168924389520'
actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:70:in `render_template_with_datadog'
actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:38:in `render_with_datadog'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
wicked_pdf (1.1.0) lib/wicked_pdf/pdf_helper.rb:42:in `render_with_wicked_pdf'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/core_extensions.rb:223:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
ddtrace (0.12.0) lib/ddtrace/contrib/rails/middlewares.rb:16:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
lograge (0.9.0) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.4) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
ddtrace (0.12.0) lib/ddtrace/contrib/rack/middlewares.rb:53:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
puma (3.4.0) lib/puma/configuration.rb:224:in `call'
puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
puma (3.4.0) lib/puma/server.rb:406:in `process_client'
puma (3.4.0) lib/puma/server.rb:271:in `block in run'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `call'
puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

### PR DESCRIPTION
**Pull request by delner**
As revealed by #445, when the hard-cap span limit is reached for a trace (~100K), the Rails renderer tracing starts mishandling spans. This is because it was relying on `tracer.call_context.current_span` which returns the last span in the context when the context fills, as opposed to the most recently instantiated span.

Although addressing the behavior of `tracer.call_context.current_span` and its equivalent `tracer.active_span` remains an issue at large, we can avoid this altogether in the Rails code.

This pull request removes "tracing context" management and context-specific code from the Rails patch altogether, and opts for a much simpler `tracer.trace` approach instead. This should resolve #445 by simply avoiding the code path in question altogether.

### CODE REVIEW

**Comment by onnimonni** [comment]
Hey @delner I work with @jvalanen and I can confirm that the slow loading page in question works correctly after using this branch. No more `undefined method `span_id' for nil:NilClass` error.

We are eagerly waiting for the next release :thumbsup:

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 1]
```diff
@@ -24,25 +24,19 @@ def patch_renderer
     end
 
     def patch_template_renderer(klass)
+      # rubocop:disable Metrics/BlockLength
       do_once(:patch_template_renderer) do
         klass.class_eval do
           def render_with_datadog(*args, &block)
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: Can methods defined here be extracted to a module?

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 2]
```diff
@@ -90,30 +99,15 @@ def patch_partial_renderer(klass)
       do_once(:patch_partial_renderer) do
         klass.class_eval do
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: Could methods defined here be extracted to a module as well ?

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 3]
```diff
@@ -122,15 +116,19 @@ def render_partial_with_datadog(*args)
...
-          # because there will be multiple concurrent contexts, depending on how
-          # many partials are nested within one another.
-          def tracing_contexts
-            @tracing_contexts ||= {}
+          private
+
+          attr_accessor :active_datadog_span
+
+          def datadog_tracer
+            Datadog.configuration[:rails][:tracer]
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: ❤️

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 4]
```diff
@@ -90,30 +99,15 @@ def patch_partial_renderer(klass)
...
+              with_datadog_span(span) { render_without_datadog(*args) }
+            end
           end
 
           def render_partial_with_datadog(*args)
             begin
-              # update the tracing context with computed values before the rendering
               template_name = Datadog::Contrib::Rails::Utils.normalize_template_name(@template.try('identifier'))
-              tracing_contexts[current_span_id][:template_name] = template_name
+              active_datadog_span.set_tag('rails.template_name', template_name) if template_name
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: `'rails.template_name'.freeze` this will avoid allocating (and then GCing) the same string multiple times within single request.

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 5]
```diff
@@ -60,8 +54,8 @@ def render_template_with_datadog(*args)
                        else
                          layout_name.try(:[], 'virtual_path')
                        end
-              @tracing_context[:template_name] = template_name
-              @tracing_context[:layout] = layout
+              active_datadog_span.set_tag('rails.template_name', template_name) if template_name
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: `freeze`ing this string might also help a bit with memory use.

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 6]
```diff
@@ -60,8 +54,8 @@ def render_template_with_datadog(*args)
...
+              active_datadog_span.set_tag('rails.layout', layout) if layout
```
Comment (pawelchcki) [inline lib/ddtrace/contrib/rails/core_extensions.rb]: `freeze`ing this string might also help a bit with memory use.

File: lib/ddtrace/contrib/rails/core_extensions.rb [hunk 7]
```diff
@@ -24,25 +24,19 @@ def patch_renderer
     end
 
     def patch_template_renderer(klass)
+      # rubocop:disable Metrics/BlockLength
```
[the remark this answers is not in the document]
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: I'm okay with that. To me, this metric seems a bit arbitrary/silly.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 1 above)
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: In theory, they could. I didn't want to do that here because doing so would depend on `prepend`, we'd end up with version differences between 1.9.3 and 2.0.0+, and then everything would get more complicated, which would increase the risk of creating more bugs. We had just experienced exactly this when we refactored the ActionController patch into a module.

I would like to do this, but we should do it in a separate PR, because its more important we have a stable, verified fix to ship first. Then when that's out, we can clean up the implementation to make things look cleaner.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 2 above)
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: Same feedback as above.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 4 above)
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: You know, I tried doing exactly this, after I saw your PR. It's actually not possible to add a constant to the module we're patching here, because it raises a dynamic constant error. The only way I could think around this is either 1) refactoring this into a module (preferable, but must defer per feedback above), or 2) defining the constant in another namespace then referencing that.

The 2nd option I could do now, it just won't be as clean.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 5 above)
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: Same as above.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 6 above)
Comment (delner) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: Same as above.

**Comment by delner** [comment]
@pawelchcki Addressed feeback. Let me know what you think.

File: lib/ddtrace/contrib/rails/core_extensions.rb (hunk 1 above)
Comment (pawelchcki) [reply lib/ddtrace/contrib/rails/core_extensions.rb]: Would moving only `def render_with_datadog` to a separate module still require 'prepend'?
